
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krpodticwssaorcvzhsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtycG9kdGljd3NzYW9yY3Z6aHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDM0MDgsImV4cCI6MjA2MjgxOTQwOH0.frXDSH6_HoX69zzQrmMSIZ--N5t3uV-lZw7ncYVYYrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true
  }
});
